# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipe_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLabel
from recipeProcessor import RecipeProcessor
from recipeDetails import RecipeDetails

class RecipeUi(object):

    def setup_ui(self, RecipeUi):
        self.filtered_search = False
        # PyQt designer version of __init__
        RecipeUi.setWindowTitle("RecipeUI")

        # Current position on page
        self._current_page_idx = 1
        self._temp_page_idx = 0

        RecipeUi.setObjectName("RecipeUi")
        RecipeUi.resize(840, 640)
        self.central_widget = QtWidgets.QWidget(RecipeUi)
        self.central_widget.setObjectName("central_widget")
        self.grid_layout_widget = QtWidgets.QWidget(self.central_widget)
        self.grid_layout_widget.setGeometry(QtCore.QRect(10, 40, 791, 531))
        self.grid_layout_widget.setObjectName("grid_layout_widget")
        self.recipe_grid = QtWidgets.QGridLayout(self.grid_layout_widget)
        self.recipe_grid.setContentsMargins(0, 0, 0, 0)
        self.recipe_grid.setObjectName("recipe_grid")
        self.bottom_row_grid = QtWidgets.QGridLayout()
        self.bottom_row_grid.setObjectName("bottom_row_grid")


        self.box_7 = QtWidgets.QGridLayout()
        self.box_7.setObjectName("box_7")
        self.recipe_img_7 = QtWidgets.QGridLayout()
        self.recipe_img_7.setObjectName("recipe_img_7")
        self.img_7_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_7_label.setObjectName("img_7_label")
        self.recipe_img_7.addWidget(self.img_7_label, 0, 0, 1, 1)
        self.box_7.addLayout(self.recipe_img_7, 0, 0, 1, 1)
        self.recipe_details_7 = QtWidgets.QGridLayout()
        self.recipe_details_7.setObjectName("recipe_details_7")
        self.recipe_headers_7 = QtWidgets.QGridLayout()
        self.recipe_headers_7.setObjectName("recipe_headers_7")
        self.label_33 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_33.setObjectName("label_33")
        self.recipe_headers_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_35.setObjectName("label_35")
        self.recipe_headers_7.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_34.setObjectName("label_34")
        self.recipe_headers_7.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_36.setObjectName("label_36")
        self.recipe_headers_7.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_11.setObjectName("label_11")
        self.recipe_headers_7.addWidget(self.label_11, 4, 0, 1, 1)
        self.recipe_details_7.addLayout(self.recipe_headers_7, 0, 0, 1, 1)
        self.recipe_values_7 = QtWidgets.QGridLayout()
        self.recipe_values_7.setObjectName("recipe_values_7")
        self.label_66 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_66.setObjectName("label_66")
        self.recipe_values_7.addWidget(self.label_66, 1, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_67.setObjectName("label_67")
        self.recipe_values_7.addWidget(self.label_67, 2, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_68.setObjectName("label_68")
        self.recipe_values_7.addWidget(self.label_68, 3, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_65.setObjectName("label_65")
        self.recipe_values_7.addWidget(self.label_65, 0, 0, 1, 1)
        self.push_button_7 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_7.setObjectName("pushButton_7")
        self.recipe_values_7.addWidget(self.push_button_7, 4, 0, 1, 1)
        self.recipe_details_7.addLayout(self.recipe_values_7, 0, 1, 1, 1)
        self.box_7.addLayout(self.recipe_details_7, 1, 0, 1, 1)
        self.bottom_row_grid.addLayout(self.box_7, 0, 2, 1, 1)
        self.box_6 = QtWidgets.QGridLayout()
        self.box_6.setObjectName("box_6")
        self.recipe_img_6 = QtWidgets.QGridLayout()
        self.recipe_img_6.setObjectName("recipe_img_6")
        self.img_6_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_6_label.setObjectName("img_6_label")
        self.recipe_img_6.addWidget(self.img_6_label, 0, 0, 1, 1)
        self.box_6.addLayout(self.recipe_img_6, 0, 0, 1, 1)
        self.recipe_details_6 = QtWidgets.QGridLayout()
        self.recipe_details_6.setObjectName("recipe_details_6")
        self.recipe_headers_6 = QtWidgets.QGridLayout()
        self.recipe_headers_6.setObjectName("recipe_headers_6")
        self.label_29 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_29.setObjectName("label_29")
        self.recipe_headers_6.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_30.setObjectName("label_30")
        self.recipe_headers_6.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_32.setObjectName("label_32")
        self.recipe_headers_6.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_31.setObjectName("label_31")
        self.recipe_headers_6.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_10.setObjectName("label_10")
        self.recipe_headers_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.recipe_details_6.addLayout(self.recipe_headers_6, 0, 0, 1, 1)
        self.recipe_values_6 = QtWidgets.QGridLayout()
        self.recipe_values_6.setObjectName("recipe_values_6")
        self.label_62 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_62.setObjectName("label_62")
        self.recipe_values_6.addWidget(self.label_62, 1, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_61.setObjectName("label_61")
        self.recipe_values_6.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_64.setObjectName("label_64")
        self.recipe_values_6.addWidget(self.label_64, 3, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_63.setObjectName("label_63")
        self.recipe_values_6.addWidget(self.label_63, 2, 0, 1, 1)
        self.push_button_6 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_6.setObjectName("pushButton_6")
        self.recipe_values_6.addWidget(self.push_button_6, 4, 0, 1, 1)
        self.recipe_details_6.addLayout(self.recipe_values_6, 0, 1, 1, 1)
        self.box_6.addLayout(self.recipe_details_6, 1, 0, 1, 1)
        self.bottom_row_grid.addLayout(self.box_6, 0, 1, 1, 1)
        self.box_5 = QtWidgets.QGridLayout()
        self.box_5.setObjectName("box_5")
        self.recipe_img_5 = QtWidgets.QGridLayout()
        self.recipe_img_5.setObjectName("recipe_img_5")
        self.img_5_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_5_label.setObjectName("img_5_label")
        self.recipe_img_5.addWidget(self.img_5_label, 0, 0, 1, 1)
        self.box_5.addLayout(self.recipe_img_5, 0, 0, 1, 1)
        self.recipe_details_5 = QtWidgets.QGridLayout()
        self.recipe_details_5.setObjectName("recipe_details_5")
        self.recipe_headers_5 = QtWidgets.QGridLayout()
        self.recipe_headers_5.setObjectName("recipe_headers_5")
        self.label_28 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_28.setObjectName("label_28")
        self.recipe_headers_5.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_27.setObjectName("label_27")
        self.recipe_headers_5.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_25.setObjectName("label_25")
        self.recipe_headers_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_26.setObjectName("label_26")
        self.recipe_headers_5.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_9.setObjectName("label_9")
        self.recipe_headers_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.recipe_details_5.addLayout(self.recipe_headers_5, 0, 0, 1, 1)
        self.recipe_values_5 = QtWidgets.QGridLayout()
        self.recipe_values_5.setObjectName("recipe_values_5")
        self.label_57 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_57.setObjectName("label_57")
        self.recipe_values_5.addWidget(self.label_57, 0, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_59.setObjectName("label_59")
        self.recipe_values_5.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_60.setObjectName("label_60")
        self.recipe_values_5.addWidget(self.label_60, 3, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_58.setObjectName("label_58")
        self.recipe_values_5.addWidget(self.label_58, 1, 0, 1, 1)
        self.push_button_5 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_5.setObjectName("pushButton_5")
        self.recipe_values_5.addWidget(self.push_button_5, 4, 0, 1, 1)
        self.recipe_details_5.addLayout(self.recipe_values_5, 0, 1, 1, 1)
        self.box_5.addLayout(self.recipe_details_5, 1, 0, 1, 1)
        self.bottom_row_grid.addLayout(self.box_5, 0, 0, 1, 1)
        self.box_8 = QtWidgets.QGridLayout()
        self.box_8.setObjectName("box_8")
        self.recipe_img_8 = QtWidgets.QGridLayout()
        self.recipe_img_8.setObjectName("recipe_img_8")
        self.img_8_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_8_label.setObjectName("img_8_label")
        self.recipe_img_8.addWidget(self.img_8_label, 0, 0, 1, 1)
        self.box_8.addLayout(self.recipe_img_8, 0, 0, 1, 1)
        self.recipe_details_8 = QtWidgets.QGridLayout()
        self.recipe_details_8.setObjectName("recipe_details_8")
        self.recipe_headers_8 = QtWidgets.QGridLayout()
        self.recipe_headers_8.setObjectName("recipe_headers_8")
        self.label_38 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_38.setObjectName("label_38")
        self.recipe_headers_8.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_40.setObjectName("label_40")
        self.recipe_headers_8.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_39.setObjectName("label_39")
        self.recipe_headers_8.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_37.setObjectName("label_37")
        self.recipe_headers_8.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_12.setObjectName("label_12")
        self.recipe_headers_8.addWidget(self.label_12, 4, 0, 1, 1)
        self.recipe_details_8.addLayout(self.recipe_headers_8, 0, 0, 1, 1)
        self.recipe_values_8 = QtWidgets.QGridLayout()
        self.recipe_values_8.setObjectName("recipe_values_8")
        self.label_72 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_72.setObjectName("label_72")
        self.recipe_values_8.addWidget(self.label_72, 3, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_71.setObjectName("label_71")
        self.recipe_values_8.addWidget(self.label_71, 2, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_70.setObjectName("label_70")
        self.recipe_values_8.addWidget(self.label_70, 1, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_69.setObjectName("label_69")
        self.recipe_values_8.addWidget(self.label_69, 0, 0, 1, 1)
        self.push_button_8 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_8.setObjectName("pushButton_8")
        self.recipe_values_8.addWidget(self.push_button_8, 4, 0, 1, 1)
        self.recipe_details_8.addLayout(self.recipe_values_8, 0, 1, 1, 1)
        self.box_8.addLayout(self.recipe_details_8, 1, 0, 1, 1)
        self.bottom_row_grid.addLayout(self.box_8, 0, 3, 1, 1)
        self.recipe_grid.addLayout(self.bottom_row_grid, 1, 0, 1, 1)
        self.top_row_grid = QtWidgets.QGridLayout()
        self.top_row_grid.setObjectName("top_row_grid")
        self.box_3 = QtWidgets.QGridLayout()
        self.box_3.setObjectName("box_3")
        self.recipe_img_3 = QtWidgets.QGridLayout()
        self.recipe_img_3.setObjectName("recipe_img_3")
        self.img_3_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_3_label.setObjectName("img_3_label")
        self.recipe_img_3.addWidget(self.img_3_label, 0, 0, 1, 1)
        self.box_3.addLayout(self.recipe_img_3, 0, 0, 1, 1)
        self.recipe_details_3 = QtWidgets.QGridLayout()
        self.recipe_details_3.setObjectName("recipe_details_3")
        self.recipe_headers_3 = QtWidgets.QGridLayout()
        self.recipe_headers_3.setObjectName("recipe_headers_3")
        self.label_19 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_19.setObjectName("label_19")
        self.recipe_headers_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_17.setObjectName("label_17")
        self.recipe_headers_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_20.setObjectName("label_20")
        self.recipe_headers_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_18.setObjectName("label_18")
        self.recipe_headers_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_7.setObjectName("label_7")
        self.recipe_headers_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.recipe_details_3.addLayout(self.recipe_headers_3, 0, 0, 1, 1)
        self.recipe_values_3 = QtWidgets.QGridLayout()
        self.recipe_values_3.setObjectName("recipe_values_3")
        self.label_49 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_49.setObjectName("label_49")
        self.recipe_values_3.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_52.setObjectName("label_52")
        self.recipe_values_3.addWidget(self.label_52, 3, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_50.setObjectName("label_50")
        self.recipe_values_3.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_51.setObjectName("label_51")
        self.recipe_values_3.addWidget(self.label_51, 2, 0, 1, 1)
        self.push_button_3 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_3.setObjectName("pushButton_3")
        self.recipe_values_3.addWidget(self.push_button_3, 4, 0, 1, 1)
        self.recipe_details_3.addLayout(self.recipe_values_3, 0, 1, 1, 1)
        self.box_3.addLayout(self.recipe_details_3, 1, 0, 1, 1)
        self.top_row_grid.addLayout(self.box_3, 0, 2, 1, 1)
        self.box_2 = QtWidgets.QGridLayout()
        self.box_2.setObjectName("box_2")
        self.recip_img_2 = QtWidgets.QGridLayout()
        self.recip_img_2.setObjectName("recip_img_2")
        self.img_2_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_2_label.setObjectName("img_2_label")
        self.recip_img_2.addWidget(self.img_2_label, 0, 0, 1, 1)
        self.box_2.addLayout(self.recip_img_2, 0, 0, 1, 1)
        self.recipe_details_2 = QtWidgets.QGridLayout()
        self.recipe_details_2.setObjectName("recipe_details_2")
        self.recipe_headers_2 = QtWidgets.QGridLayout()
        self.recipe_headers_2.setObjectName("recipe_headers_2")
        self.label_16 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_16.setObjectName("label_16")
        self.recipe_headers_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_14.setObjectName("label_14")
        self.recipe_headers_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_15.setObjectName("label_15")
        self.recipe_headers_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_13.setObjectName("label_13")
        self.recipe_headers_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_6.setObjectName("label_6")
        self.recipe_headers_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.recipe_details_2.addLayout(self.recipe_headers_2, 0, 0, 1, 1)
        self.recipe_values_2 = QtWidgets.QGridLayout()
        self.recipe_values_2.setObjectName("recipe_values_2")
        self.label_47 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_47.setObjectName("label_47")
        self.recipe_values_2.addWidget(self.label_47, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_48.setObjectName("label_48")
        self.recipe_values_2.addWidget(self.label_48, 3, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_46.setObjectName("label_46")
        self.recipe_values_2.addWidget(self.label_46, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_45.setObjectName("label_45")
        self.recipe_values_2.addWidget(self.label_45, 0, 0, 1, 1)
        self.push_button_2 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_2.setObjectName("pushButton_2")
        self.recipe_values_2.addWidget(self.push_button_2, 4, 0, 1, 1)
        self.recipe_details_2.addLayout(self.recipe_values_2, 0, 1, 1, 1)
        self.box_2.addLayout(self.recipe_details_2, 1, 0, 1, 1)
        self.top_row_grid.addLayout(self.box_2, 0, 1, 1, 1)
        self.box_1 = QtWidgets.QGridLayout()
        self.box_1.setObjectName("box_1")
        self.img_1 = QtWidgets.QGridLayout()
        self.img_1.setObjectName("img_1")
        self.img_1_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_1_label.setObjectName("img_1_label")
        self.img_1.addWidget(self.img_1_label, 0, 0, 1, 1)
        self.box_1.addLayout(self.img_1, 0, 0, 1, 1)
        self.recipe_details_1 = QtWidgets.QGridLayout()
        self.recipe_details_1.setObjectName("recipe_details_1")
        self.recipe_headers_1 = QtWidgets.QGridLayout()
        self.recipe_headers_1.setObjectName("recipe_headers_1")
        self.label_2 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_2.setObjectName("label_2")
        self.recipe_headers_1.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_4.setObjectName("label_4")
        self.recipe_headers_1.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.grid_layout_widget)
        self.label.setObjectName("label")
        self.recipe_headers_1.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_3.setObjectName("label_3")
        self.recipe_headers_1.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_5.setObjectName("label_5")
        self.recipe_headers_1.addWidget(self.label_5, 4, 0, 1, 1)
        self.recipe_details_1.addLayout(self.recipe_headers_1, 0, 0, 1, 1)
        self.recipe_values_1 = QtWidgets.QGridLayout()
        self.recipe_values_1.setObjectName("recipe_values_1")
        self.label_42 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_42.setObjectName("label_42")
        self.recipe_values_1.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_44.setObjectName("label_44")
        self.recipe_values_1.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_41.setObjectName("label_41")
        self.recipe_values_1.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_43.setObjectName("label_43")
        self.recipe_values_1.addWidget(self.label_43, 2, 0, 1, 1)
        self.push_button = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button.setObjectName("pushButton")
        self.recipe_values_1.addWidget(self.push_button, 4, 0, 1, 1)
        self.recipe_details_1.addLayout(self.recipe_values_1, 0, 1, 1, 1)
        self.box_1.addLayout(self.recipe_details_1, 1, 0, 1, 1)
        self.top_row_grid.addLayout(self.box_1, 0, 0, 1, 1)
        self.box_4 = QtWidgets.QGridLayout()
        self.box_4.setObjectName("box_4")
        self.recipe_img_4 = QtWidgets.QGridLayout()
        self.recipe_img_4.setObjectName("recipe_img_4")
        self.img_4_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.img_4_label.setObjectName("img_4_label")
        self.recipe_img_4.addWidget(self.img_4_label, 0, 0, 1, 1)
        self.box_4.addLayout(self.recipe_img_4, 0, 0, 1, 1)
        self.recipe_details_4 = QtWidgets.QGridLayout()
        self.recipe_details_4.setObjectName("recipe_details_4")
        self.recipe_headers_4 = QtWidgets.QGridLayout()
        self.recipe_headers_4.setObjectName("recipe_headers_4")
        self.label_24 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_24.setObjectName("label_24")
        self.recipe_headers_4.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_22.setObjectName("label_22")
        self.recipe_headers_4.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_23.setObjectName("label_23")
        self.recipe_headers_4.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_21.setObjectName("label_21")
        self.recipe_headers_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_8.setObjectName("label_8")
        self.recipe_headers_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.recipe_details_4.addLayout(self.recipe_headers_4, 0, 0, 1, 1)
        self.recipe_values_4 = QtWidgets.QGridLayout()
        self.recipe_values_4.setObjectName("recipe_values_4")
        self.label_53 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_53.setObjectName("label_53")
        self.recipe_values_4.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_55.setObjectName("label_55")
        self.recipe_values_4.addWidget(self.label_55, 2, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_56.setObjectName("label_56")
        self.recipe_values_4.addWidget(self.label_56, 3, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.grid_layout_widget)
        self.label_54.setObjectName("label_54")
        self.recipe_values_4.addWidget(self.label_54, 1, 0, 1, 1)
        self.push_button_4 = QtWidgets.QPushButton(self.grid_layout_widget)
        self.push_button_4.setObjectName("pushButton_4")
        self.recipe_values_4.addWidget(self.push_button_4, 4, 0, 1, 1)
        self.recipe_details_4.addLayout(self.recipe_values_4, 0, 1, 1, 1)
        self.box_4.addLayout(self.recipe_details_4, 1, 0, 1, 1)
        self.top_row_grid.addLayout(self.box_4, 0, 3, 1, 1)
        self.recipe_grid.addLayout(self.top_row_grid, 0, 0, 1, 1)
        self.grid_layout_widget_2 = QtWidgets.QWidget(self.central_widget)
        self.grid_layout_widget_2.setGeometry(QtCore.QRect(10, 0, 791, 41))
        self.grid_layout_widget_2.setObjectName("grid_layout_widget_2")
        self.search_grid = QtWidgets.QGridLayout(self.grid_layout_widget_2)
        self.search_grid.setContentsMargins(0, 0, 0, 0)
        self.search_grid.setObjectName("search_grid")
        self.search_bar = QtWidgets.QLineEdit(self.grid_layout_widget_2)
        self.search_bar.setObjectName("search_bar")
        self.search_grid.addWidget(self.search_bar, 0, 0, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.grid_layout_widget_2)
        self.search_button.setObjectName("search_button")
        self.search_grid.addWidget(self.search_button, 0, 1, 1, 1)
        self.reset_button = QtWidgets.QPushButton(self.grid_layout_widget_2)
        self.reset_button.setObjectName("reset_button")
        self.search_grid.addWidget(self.reset_button, 0, 2, 1, 1)
        self.grid_layout_widget_3 = QtWidgets.QWidget(self.central_widget)
        self.grid_layout_widget_3.setGeometry(QtCore.QRect(510, 570, 320, 51))
        self.grid_layout_widget_3.setObjectName("grid_layout_widget_3")
        self.pagination_buttons = QtWidgets.QGridLayout(self.grid_layout_widget_3)
        self.pagination_buttons.setContentsMargins(0, 0, 0, 0)
        self.pagination_buttons.setObjectName("pagination_buttons")
        self.next_button = QtWidgets.QPushButton(self.grid_layout_widget_3)
        self.next_button.setObjectName("next_button")
        self.pagination_buttons.addWidget(self.next_button, 0, 3, 1, 1)
        self.first_button = QtWidgets.QPushButton(self.grid_layout_widget_3)
        self.first_button.setObjectName("first_button")
        self.pagination_buttons.addWidget(self.first_button, 0, 1, 1, 1)
        self.previous_button = QtWidgets.QPushButton(self.grid_layout_widget_3)
        self.previous_button.setObjectName("previous_button")
        self.pagination_buttons.addWidget(self.previous_button, 0, 0, 1, 1)
        self.last_button = QtWidgets.QPushButton(self.grid_layout_widget_3)
        self.last_button.setObjectName("last_button")
        self.pagination_buttons.addWidget(self.last_button, 0, 2, 1, 1)
        RecipeUi.setCentralWidget(self.central_widget)
        self.status_bar = QtWidgets.QStatusBar(RecipeUi)
        self.status_bar.setObjectName("status_bar")
        RecipeUi.setStatusBar(self.status_bar)
        self._temp_list = []

        # List of image, recipe name, prep time, and cook time layouts for easy access:
        self._img_layouts = [self.img_1_label, self.img_2_label, self.img_3_label, self.img_4_label, self.img_5_label,
                             self.img_6_label, self.img_7_label, self.img_8_label]

        self._num_layouts = [self.label_41, self.label_45, self.label_49, self.label_53, self.label_57, self.label_61,
                              self.label_65, self.label_69]

        self._name_layouts = [self.label_42, self.label_46, self.label_50, self.label_54, self.label_58, self.label_62,
                              self.label_66, self.label_70]

        self._prep_layouts = [self.label_43, self.label_47, self.label_51, self.label_55, self.label_59, self.label_63,
                              self.label_67, self.label_71]

        self._cook_layouts = [self.label_44, self.label_48, self.label_52, self.label_56, self.label_60, self.label_64,
                              self.label_68, self.label_72]

        self.retranslate_ui(RecipeUi)
        QtCore.QMetaObject.connectSlotsByName(RecipeUi)

        # Load up recipe processor
        self._recipe_processor = RecipeProcessor()
        self._recipe_processor.load_recipes("recipes.json")
        self._recipes = self._recipe_processor.get_recipe_list()

        # Child dialogue class with recipe processor
        self._dialogue = RecipeDetails(self._recipe_processor)

        self._begin_recipes = []
        for i in range(8):
            self._begin_recipes.append(self._recipes[i])

        self.layout_ui(self._begin_recipes)

    def layout_ui(self, recipes):
        # Initially, load first 8 images and their respective descriptions
        for i in range(8):
            self._rand_recipe = recipes[i]
            self.insert_details(i, self._rand_recipe, i + 1)

        self.status_bar.showMessage(
            f"Displaying 1-8 of {self._recipe_processor.get_num_recipes()} recipes")
        self.home()


    # Method to insert image into appropriate label
    def insert_details(self, box_no, recipe, recipe_num):
        _translate = QtCore.QCoreApplication.translate
        # Place image in box
        img_name = recipe.get_image()
        img_bytes = open(img_name, "rb").read()

        curr_image = QImage()
        curr_image.loadFromData(img_bytes)
        # Parent set to appropriate image grid
        self._pic_label = QLabel(self._img_layouts[box_no])

        new_pixmap = QPixmap.fromImage(curr_image)
        new_pixmap = new_pixmap.scaled(188, 124, Qt.KeepAspectRatio)
        self._pic_label.setPixmap(new_pixmap)

        # Do the same with all details and word wrap for name
        self._num_layouts[box_no].setText(_translate("RecipeUi", str(recipe_num)))
        self._name_layouts[box_no].setWordWrap(True)
        self._name_layouts[box_no].setText(_translate("RecipeUi", recipe.get_name()))
        self._prep_layouts[box_no].setText(_translate("RecipeUi", str(recipe.get_prep_time())))
        self._cook_layouts[box_no].setText(_translate("RecipeUi", str(recipe.get_cook_time())))

    def home(self):
        self.next_button.clicked.connect(self.next)
        self.previous_button.clicked.connect(self.prev)
        self.first_button.clicked.connect(self.first)
        self.last_button.clicked.connect(self.last)
        self.search_button.clicked.connect(lambda clicked, text=self.search_bar.text(): self.search(text))
        self.reset_button.clicked.connect(self.reset)
        self.push_button.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx - 1: self._dialogue.displayRecipe(recipe_num))
        self.push_button_2.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx: self._dialogue.displayRecipe(recipe_num))
        self.push_button_3.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 1: self._dialogue.displayRecipe(recipe_num))
        self.push_button_4.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 2: self._dialogue.displayRecipe(recipe_num))
        self.push_button_5.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 3: self._dialogue.displayRecipe(recipe_num))
        self.push_button_6.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 4: self._dialogue.displayRecipe(recipe_num))
        self.push_button_7.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 5: self._dialogue.displayRecipe(recipe_num))
        self.push_button_8.clicked.connect(
            lambda clicked, recipe_num=self._current_page_idx + 6: self._dialogue.displayRecipe(recipe_num))

    # Iterate through all lists to see if string is present in strings: creates new list to search through
    def search(self, recipe_keywords):
        self._filtered_list = []
        for recipe in self._recipes:
            if recipe_keywords in recipe.get_name() or recipe_keywords in recipe.get_description() or recipe_keywords in recipe.get_ingredients():
                self._filtered_list.append(recipe)
                self.filtered_search = True

        if len(self._filtered_list) != 0:
            for rec in self._filtered_list:
                print(rec.get_name())
            self.next()

    # Display next set of images
    def next(self):
        self._temp_list = self._recipe_processor.get_recipe_list()

        # If there are more things to display, go to next page
        if self.filtered_search == True:
            self._temp_list = self._filtered_list

        if self._current_page_idx < len(self._temp_list):
            # Clear page then display up to 8 more recipes, if there are that many present
            for i in range(8):
                _translate = QtCore.QCoreApplication.translate
                self._img_layouts[i].setPixmap(QtGui.QPixmap())
                self._num_layouts[i].setText(_translate("RecipeUi", ""))
                self._name_layouts[i].setText(_translate("RecipeUi", ""))
                self._prep_layouts[i].setText(_translate("RecipeUi", ""))
                self._cook_layouts[i].setText(_translate("RecipeUi", ""))

            self._current_page_idx += 8
            self._temp_page_idx = self._current_page_idx - 1
            i = 0
            while self._temp_page_idx < len(self._temp_list) and i < 8:
                self.insert_details(i, self._temp_list[self._temp_page_idx], self._temp_page_idx)
                self._temp_page_idx += 1
                i += 1

            self.status_bar.showMessage(f"Displaying {self._current_page_idx}-{self._temp_page_idx} of {len(self._temp_list)} recipes")

    def prev(self):
        self._temp_list = self._recipe_processor.get_recipe_list()

        # If there are more things to display, go to next page
        if self.filtered_search == True:
            self._temp_list = self._filtered_list

        # If there are more things to display, go to next page
        if self._current_page_idx > 8:
            # Clear page then display up to 8 more recipes, if there are that many present
            for i in range(8):
                _translate = QtCore.QCoreApplication.translate
                self._pic_label.setPixmap(QtGui.QPixmap())
                self._num_layouts[i].setText(_translate("RecipeUi", ""))
                self._name_layouts[i].setText(_translate("RecipeUi", ""))
                self._prep_layouts[i].setText(_translate("RecipeUi", ""))
                self._cook_layouts[i].setText(_translate("RecipeUi", ""))

            self._current_page_idx -= 8
            self._temp_page_idx = self._current_page_idx
            self._max = self._current_page_idx + 7
            i = 0
            while self._temp_page_idx < len(self._temp_list) and i < 8:
                self.insert_details(i, self._temp_list[self._temp_page_idx], self._temp_page_idx)
                self._temp_page_idx += 1
                i += 1

            self.status_bar.showMessage(f"Displaying {self._current_page_idx}-{self._max} of {len(self._temp_list)} recipes")


    def first(self):
        self._temp_list = self._recipe_processor.get_recipe_list()

        # If there are more things to display, go to next page
        if self.filtered_search == True:
            self._temp_list = self._filtered_list

        # Clear page then display up to 8 more recipes, if there are that many present
        for i in range(8):
            _translate = QtCore.QCoreApplication.translate
            self._pic_label.setPixmap(QtGui.QPixmap())
            self._num_layouts[i].setText(_translate("RecipeUi", ""))
            self._name_layouts[i].setText(_translate("RecipeUi", ""))
            self._prep_layouts[i].setText(_translate("RecipeUi", ""))
            self._cook_layouts[i].setText(_translate("RecipeUi", ""))

        # Current position on page
        self._current_page_idx = 1
        self._temp_page_idx = 0

        for i in range(8):
            if i == 8:
                break
            self._rand_recipe = self._temp_list[i]
            self.insert_details(i, self._rand_recipe, i + 1)


        self.status_bar.showMessage(
            f"Displaying 1-8 of {len(self._temp_list)} recipes")

    def last(self):
        self._temp_list = self._recipe_processor.get_recipe_list()

        # If there are more things to display, go to next page
        if self.filtered_search == True:
            self._temp_list = self._filtered_list

        # Clear page then display up to 8 more recipes, if there are that many present
        for i in range(8):
            _translate = QtCore.QCoreApplication.translate
            self._pic_label.setPixmap(QtGui.QPixmap())
            self._num_layouts[i].setText(_translate("RecipeUi", ""))
            self._name_layouts[i].setText(_translate("RecipeUi", ""))
            self._prep_layouts[i].setText(_translate("RecipeUi", ""))
            self._cook_layouts[i].setText(_translate("RecipeUi", ""))

        # Current position on page
        self._current_page_idx = len(self._temp_list) - 7

        i = 0
        for k in range(self._current_page_idx, len(self._temp_list)):
            self._rand_recipe = self._temp_list[k]
            self.insert_details(i, self._rand_recipe, k + 1)
            i += 1

        self.status_bar.showMessage(
            f"Displaying {self._current_page_idx}-{len(self._temp_list)} of {len(self._temp_list)} recipes")

    def reset(self):
        self._temp_list.clear()
        self._filtered_list = []
        self.filtered_search = False
        self.first()

    def retranslate_ui(self, RecipeUi):
        _translate = QtCore.QCoreApplication.translate
        RecipeUi.setWindowTitle(_translate("RecipeUi", "MainWindow"))
        self.img_7_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_33.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_35.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_34.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_36.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_11.setText(_translate("RecipeUi", " "))
        self.label_66.setText(_translate("RecipeUi", "FILL_NAME_7"))
        self.label_67.setText(_translate("RecipeUi", "FILL_PREP_7"))
        self.label_68.setText(_translate("RecipeUi", "FILL_COOK_7"))
        self.label_65.setText(_translate("RecipeUi", "FILLNUM_7"))
        self.push_button_7.setText(_translate("RecipeUi", "View Recipe"))
        self.img_6_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_29.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_30.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_32.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_31.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_10.setText(_translate("RecipeUi", " "))
        self.label_62.setText(_translate("RecipeUi", "FILL_NAME_6"))
        self.label_61.setText(_translate("RecipeUi", "FILLNUM_6"))
        self.label_64.setText(_translate("RecipeUi", "FILL_COOK_6"))
        self.label_63.setText(_translate("RecipeUi", "FILL_PREP_6"))
        self.push_button_6.setText(_translate("RecipeUi", "View Recipe"))
        self.img_5_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_28.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_27.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_25.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_26.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_9.setText(_translate("RecipeUi", " "))
        self.label_57.setText(_translate("RecipeUi", "FILLNUM_5"))
        self.label_59.setText(_translate("RecipeUi", "FILL_PREP_5"))
        self.label_60.setText(_translate("RecipeUi", "FILL_COOK_5"))
        self.label_58.setText(_translate("RecipeUi", "FILL_NAME_5"))
        self.push_button_5.setText(_translate("RecipeUi", "View Recipe"))
        self.img_8_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_38.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_40.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_39.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_37.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_12.setText(_translate("RecipeUi", " "))
        self.label_72.setText(_translate("RecipeUi", "FILL_COOK_8"))
        self.label_71.setText(_translate("RecipeUi", "FILL_PREP_8"))
        self.label_70.setText(_translate("RecipeUi", "FILL_NAME_8"))
        self.label_69.setText(_translate("RecipeUi", "FILLNUM_8"))
        self.push_button_8.setText(_translate("RecipeUi", "View Recipe"))
        self.img_3_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_19.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_17.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_20.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_18.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_7.setText(_translate("RecipeUi", " "))
        self.label_49.setText(_translate("RecipeUi", "FILLNUM_3"))
        self.label_52.setText(_translate("RecipeUi", "FILL_COOK_3"))
        self.label_50.setText(_translate("RecipeUi", "FILL_NAME_3"))
        self.label_51.setText(_translate("RecipeUi", "FILL_PREP_3"))
        self.push_button_3.setText(_translate("RecipeUi", "View Recipe"))
        self.img_2_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_16.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_14.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_15.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_13.setText(_translate("RecipeUi", "Recipe #"))
        self.label_6.setText(_translate("RecipeUi", " "))
        self.label_47.setText(_translate("RecipeUi", "FILL_PREP_2"))
        self.label_48.setText(_translate("RecipeUi", "FILL_COOK_2"))
        self.label_46.setText(_translate("RecipeUi", "FILL_NAME_2"))
        self.label_45.setText(_translate("RecipeUi", "FILLNUM_2"))
        self.push_button_2.setText(_translate("RecipeUi", "View Recipe"))
        self.img_1_label.setText(_translate("RecipeUi", "IMG_1_ACTUAL"))
        self.label_2.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_4.setText(_translate("RecipeUi", "Cook Time:"))
        self.label.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_3.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_5.setText(_translate("RecipeUi", " "))
        self.label_42.setText(_translate("RecipeUi", "FILL_NAME_1"))
        self.label_44.setText(_translate("RecipeUi", "FILL_COOK_1"))
        self.label_41.setText(_translate("RecipeUi", "FILLNUM_1"))
        self.label_43.setText(_translate("RecipeUi", "FILL_PREP_1"))
        self.push_button.setText(_translate("RecipeUi", "View Recipe"))
        self.img_4_label.setText(_translate("RecipeUi", "TextLabel"))
        self.label_24.setText(_translate("RecipeUi", "Cook Time:"))
        self.label_22.setText(_translate("RecipeUi", "Recipe Name:"))
        self.label_23.setText(_translate("RecipeUi", "Prep Time:"))
        self.label_21.setText(_translate("RecipeUi", "Recipe #:"))
        self.label_8.setText(_translate("RecipeUi", " "))
        self.label_53.setText(_translate("RecipeUi", "FILLNUM_4"))
        self.label_55.setText(_translate("RecipeUi", "FILL_PREP_4"))
        self.label_56.setText(_translate("RecipeUi", "FILL_COOK_4"))
        self.label_54.setText(_translate("RecipeUi", "FILL_NAME_4"))
        self.push_button_4.setText(_translate("RecipeUi", "View Recipe"))
        self.search_button.setText(_translate("RecipeUi", "Search"))
        self.reset_button.setText(_translate("RecipeUi", "Reset"))
        self.next_button.setText(_translate("RecipeUi", "Next >>"))
        self.first_button.setText(_translate("RecipeUi", "First"))
        self.previous_button.setText(_translate("RecipeUi", "<< Previous"))
        self.last_button.setText(_translate("RecipeUi", "Last"))

def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recipe_ui = QtWidgets.QMainWindow()
    ui = RecipeUi()
    ui.setup_ui(recipe_ui)
    recipe_ui.show()
    sys.exit(app.exec_())


main()
